---
- name: Copy root files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
    group: root
    force: true
    mode: >
      0700
    owner: "root"
  loop:
    - '.bash_profile'
    - '.bashrc'
    - '.gitconfig'
    - '.vimrc'
- name: Template wakatime config
  ansible.builtin.template:
    src: .wakatime.cfg.j2
    dest: /root/.wakatime.cfg
    owner: root
    group: root
    mode: "ug+rw"
- name: Install some programs
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - ansible
    - git
    - networkmanager
- name: Add groups
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - ansible
    - git
- name: Ensure uniform wifi backend
  ansible.builtin.copy:
    src: wifi_backend.conf
    dest: /etc/NetworkManager/conf.d/wifi_backend.conf
    owner: root
    group: root
    mode: ug+rw
  notify: 'Restart NetworkManager'
