---
- name: Install containerd
  community.general.pacman:
    name: containerd
    state: present
- name: Create config directory
  ansible.builtin.file:
    dest: /etc/containerd
    state: directory
    mode: ug+rwx
- name: Copy cgroup config
  ansible.builtin.copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    mode: ug+rw,o+r
- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    enabled: true
    state: restarted
