# SPDX-License-Identifier: MIT-0
---
# vars file for ansible
packages_list:
  - direnv
  - expac
  - fd
  - fzf
  - ghostscript
  - glances
  - imagemagick
  - irssi
  - lazygit
  - lua51
  - luarocks
  - mermaid-cli
  - navi
  - nodejs
  - python-pynvim
  - ripgrep
  - rsyslog
  - rubygems
  - tectonic
  - texlive-bin
  - tldr
  - tree-sitter
  - tree-sitter-cli
