---
- name: Install and configure kube-controller-manager
  hosts: kcp
  remote_user: duchess
  tasks:
    - name: Install kube-controller-manager
      ansible.builtin.command:
        cmd: 'yay -Syuu kube-controller-manager --noconfirm'
        creates: /usr/bin/kube-controller-manager
    - name: Install kube-controller-manager completion
      ansible.builtin.copy:
        src: kube-controller-manager.completion
        dest: /usr/share/bash-completion/completions/kube-controller-manager.completion
        owner: root
        group: kube
        mode: 'u+rw,g+rw'
      become: true
    - name: Copy kcm.sh
      ansible.builtin.copy:
        src: kcm.sh
        dest: /usr/sbin/kcm.sh
        owner: root
        group: kube
        mode: 'u+rwx,g+rwx'
      become: true
    - name: Copy systemd service
      ansible.builtin.copy:
        src: kube-controller-manager.service
        dest: /usr/lib/systemd/system/kube-controller-manager.service
        owner: root
        group: kube
        mode: 'u+rw,g+rw'
      become: true
    - name: Start and enable kube-controller-manager
      ansible.builtin.service:
        name: kube-controller-manager
        state: started
        enabled: true
      become: true
