---
- name: Init SA user
  hosts: backup
  roles:
    - role: user
      tags:
        - sa
- name: Init user
  hosts: backup
  roles:
    - role: user
      tags:
        - user
- name: Init root user
  hosts: backup
  roles:
    - role: user
      tags:
        - root
