on:
  push:

name: Run ShellCheck
permissions: {}

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          # A space separated list of additional filename to check
          #additional_files: # optional, default is
          # Paths to ignore when running ShellCheck
          # ignore: # optional, default is IN
          # Paths to ignore when running ShellCheck
          #ignore_paths: # optional, default is
          # Names to ignore when running ShellCheck
          #ignore_names: # optional, default is
          # Minimum severity of errors to consider. Options: [error, warning, info, style]
          #severity: # optional, default is
          # Run shellcheck on _all_ files at once, instead of one at a time
          check_together: yes
          # Directory to be searched for files. Defaults to .
          #scandir: # optional, default is .
          # Set to true to skip using problem-matcher
          #disable_matcher: # optional, default is false
          # Output format (checkstyle, diff, gcc, json, json1, quiet, tty)
          #format: # optional, default is gcc
          # Specify a concrete version of ShellCheck to use
          #version: # optional, default is stable
