# SPDX-License-Identifier: MIT-0
---
# tasks file for packages
- name: Install extra packages
  ansible.builtin.command:
    cmd: >-
      yay -Syyu --noconfirm {{ packages_item }}
    creates: >-
      ~/.cache/yay/{{ packages_item }}
  loop: >-
    {{ packages_list }}
  loop_control:
    loop_var: packages_item
