# SPDX-License-Identifier: MIT-0
---
# tasks file for k8s
- name: Install k8s utilities
  ansible.builtin.command:
    cmd: >-
      yay -Syyu --noconfirm {{ item }}
    creates: >-
      /usr/bin/{{ item }}
  loop:
    - kubelet
    - kubeadm
    - kubie
    - kubectl
