---
- name: Install LVM package
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - lvm2
    - parted
- name: Start LVM services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - lvm2-monitor
- name: Create a new primary partition for LVM
  community.general.parted:
    device: "{{ volumes_devices[inventory_hostname].usb.device }}"
    flags:
      - lvm
    label: gpt
    name: usb
    number: 1
    part_end: 100%
    state: present
- name: Unmount local
  ansible.posix.mount:
    state: unmounted
    path: /mnt/local
- name: Drop local from fstab
  ansible.posix.mount:
    state: absent_from_fstab
    path: /mnt/local
- name: Create lvm fs
  community.general.filesystem:
    dev: "{{ volumes_devices[inventory_hostname].local.partition }}"
    fstype: lvm
    state: present
- name: Create USB LVM group
  community.general.lvg:
    vg: vg.usb
    pvs: "{{ volumes_devices[inventory_hostname].usb.device }}1"
    state: present
- name: Create local LVM group
  community.general.lvg:
    vg: vg.local
    force: true
    pvs: "{{ volumes_devices[inventory_hostname].local.partition }}"
    state: present
