- name: Install nautobot and requirements
  hosts: np
  remote_user: duchess
  tasks:
    - name: Install PostgreSQL 13
      ansible.builtin.command:
        cmd: "yay -Syyu {{ item }} --noconfirm"
        creates: /usr/bin/psql
      loop:
        - postgresql13
        - postgresql13-docs
        - postgresql13-lib
    - name: Ensure user groups
      ansible.builtin.user:
        name: "{{ item }}"
        groups: postgres
        append: true
      become: true
      loop:
        - root
        - duchess
