- name: Install and start PostgreSQL
  hosts: np
  remote_user: duchess
  tasks:
    - name: Install PostgreSQL 13
      ansible.builtin.command:
        cmd: "yay -Syyu {{ item }} --noconfirm"
        creates: /usr/bin/psql
      loop:
        - postgresql13-docs
        - postgresql13-lib
        - postgresql13
        - python-psycopg2
    - name: Ensure user groups
      ansible.builtin.user:
        name: "{{ item }}"
        groups: postgres
        append: true
      become: true
      loop:
        - root
        - duchess
    - name: Verify permissions
      ansible.builtin.file:
        path: /var/lib/postgres
        state: directory
        recurse: true
        owner: postgres
        group: postgres
      become: true
    - name: Initialize data directory
      ansible.builtin.command:
        cmd: >-
          su - postgres -c "initdb --locale en_US.UTF-8 -D '/var/lib/postgres/data'"
        creates: /var/lib/postgres/data/postgresql.conf
      become: true
    - name: Start and enable Postgres
      ansible.builtin.service:
        name: postgresql
        state: restarted
        enabled: true
      become: true
    - name: Add a user for nautobot
      community.postgresql.postgresql_user:
        name: nautobot
        state: present
        password: "{{ pgsql_password }}"
      become: true
      become_user: postgres
    - name: Add a database for nautobot
      community.postgresql.postgresql_db:
        name: nautobot
        login_user: postgres
        state: present
        owner: nautobot
      become: true
      become_user: postgres
      tags:
        - db
- name: Install and start Redis
  hosts: np
  remote_user: duchess
  tasks:
    - name: Install Redis 6
      ansible.builtin.command:
        cmd: "yay -Syyu --noconfirm redis6"
        creates: /usr/lib/systemd/system/redis6.service
    - name: Link files
      ansible.builtin.file:
        src: "/usr/bin/{{ item.src }}"
        dest: "/usr/bin/{{ item.dest }}"
        state: link
      become: true
      loop:
        - src: "redis{6}-benchmark"
          dest: "redis6-benchmark"
        - src: "redis{6}-cli"
          dest: "redis6-cli"
        - src: "redis{6}-server"
          dest: "redis6-server"
        - src: "redis{6}-server"
          dest: "redis-server"
      tags:
        - redis
    - name: Start and enable Redis
      ansible.builtin.service:
        name: redis6
        state: restarted
        enabled: true
      become: true
      tags:
        - redis
    - name: Ensure user groups
      ansible.builtin.user:
        name: "{{ item }}"
        groups: redis
        append: true
      become: true
      loop:
        - root
        - duchess
