- name: Install yay package manager
  hosts: all
  remote_user: duchess
  tasks:
    - name: Update packages
      community.general.pacman:
        upgrade: true
        update_cache: true
      become: true
    - name: Install packages
      community.general.pacman:
        name: "{{ item }}"
        update_cache: true
      become: true
      loop:
        - base-devel
        - netdata
        - python
        - python-pip
    - name: Enable and start netdata
      ansible.builtin.service:
        name: netdata
        state: restarted
        enabled: true
      become: true
    - name: Clone the Yay repository
      ansible.builtin.git:
        accept_hostkey: true
        clone: true
        dest: /home/duchess/Documents/src/aur.archlinux.org/yay
        repo: https://aur.archlinux.org/yay.git # noqa: latest
    - name: Install the Yay package
      ansible.builtin.command:
        chdir: /home/duchess/Documents/src/aur.archlinux.org/yay
        cmd: makepkg -si
        creates: /usr/bin/yay
    - name: Copy the user dotfiles
      ansible.builtin.copy:
        src: "./user/{{ item }}"
        dest: "/home/duchess/{{ item }}"
        owner: duchess
        group: users
        mode: 'u+rw'
      loop:
        - .bash_profile
        - .bashrc
        - .gitconfig
        - .profile
        - .vimrc
        - .wakatime.cfg
      become: true
    - name: Copy the root dotfiles
      ansible.builtin.copy:
        src: "./root/{{ item }}"
        dest: "/root/{{ item }}"
        owner: root
        group: root
        mode: 'u+rw'
      loop:
        - .bash_profile
        - .bashrc
        - .gitconfig
        - .profile
        - .vimrc
        - .wakatime.cfg
      become: true
