# SPDX-License-Identifier: MIT-0
---
- name: Install packages
  community.general.pacman:
    name: >-
      {{ item }}
    state: present
  loop:
    - ansible
    - direnv
    - glances
    - gmotd
    - hddtemp
    - mosh
    - pkgstats
    - pre-commit
    - python-pip
    - python-virtualenv
  become: true
- name: Update package cache
  community.general.pacman:
    executable: yay
    update_cache: true
- name: Install glances
  ansible.builtin.pip:
    virtualenv: /etc/glances/
    name: >-
      {{ item }}
    state: present
  loop:
    - pip
    - glances
    - zeroconf
  become: true
- name: Install glances services
  ansible.builtin.copy:
    src: >-
      {{ item }}
    dest: >-
      /usr/lib/systemd/system/{{ item }}
    owner: root
    group: root
    mode: ug+rw
  loop:
    - glances.service
  become: true
- name: Start glances services
  ansible.builtin.service:
    name: >-
      {{ item }}
    state: started
    enabled: true
  loop:
    - glances
  become: true
- name: Enable gmotd on ssh
  ansible.builtin.copy:
    src: pam.d/sshd
    dest: /etc/pam.d/sshd
    owner: root
    group: root
    mode: ug+rw
  become: true
- name: Configure basic gmotd
  ansible.builtin.copy:
    src: gmotd.yml
    dest: /etc/gmotd/gmotd.yml
    owner: root
    group: root
    mode: ug+rw
  become: true
