- name: Copy files to users
  ansible.builtin.copy:
    src: "arch/user/{{ item }}"
    dest: "/home/{{ users }}/{{ item }}"
    owner: "{{ users }}"
    mode: "u+rw,g+r,o+r"
  loop:
    - '.bash_profile'
    - '.bashrc'
    - '.gitconfig'
    - '.vimrc'
    - '.wakatime.cfg'
  become: true
  become_user: "{{ users }}"

# code: language=ansible
