---
- name: Copy root configs
  hosts: kcp,k8s
  remote_user: duchess
  roles:
    - role: root
      tags:
        - root
  become: true
- name: Init One
  hosts: kcp,k8s
  remote_user: duchess
  roles:
    - role: users
      tags:
        - users
    - role: containerd
      tags:
        - containerd
      become: true
- name: Join Nodes
  hosts: k8s
  roles:
    - role: k8s
      tags:
        - join
      become: true
    - role: volumes
      tags:
        - volumes
      become: true
- name: Init Control Planes
  become: true
  hosts: kcp02
  remote_user: duchess
  roles:
    - role: kcp
      tags:
        - kcp
# code: language=ansible
