---
- name: Copy root configs
  hosts: hap01.breeze-blocks.net 
  remote_user: duchess
  roles:
    - role: root
      tags:
        - root
  become: true
- name: Init One
  hosts: hap01.breeze-blocks.net # local,k8s,kcp
  remote_user: duchess
  roles:
    - role: users
      tags:
        - users
    - role: containerd
      tags:
        - containerd
      become: true
    - role: logrotate
      tags:
        - logrotate
      become: true
- name: Join Nodes
  hosts: k8s
  roles:
    - role: k8s
      tags:
        - join
      become: true
    - role: volumes
      tags:
        - volumes
      become: true
    - role: lvm
      tags:
        - lvm
      become: true
    - role: nfs
      tags:
        - nfs
      become: true
- name: Init Control Planes
  become: true
  hosts: kcp
  remote_user: duchess
  roles:
    - role: kcp
      tags:
        - kcp
# code: language=ansible
