# SPDX-License-Identifier: MIT-0
---
# handlers file for ansible
- name: Restart rsyslog
  ansible.builtin.service:
<<<<<<< Updated upstream
    name: rsyslog
=======
    name: prometheus-node-exporter
>>>>>>> Stashed changes
    state: restarted
    enabled: true
