# SPDX-License-Identifier: MIT-0
---
- name: enable node exporter
  ansible.builtin.service:
    name: prometheus-node-exporfer
    state: restarted
    enabled: true
  become: true
- name: start systemd exporter
  ansible.builtin.service:
    name: prometheus-systemd-exporter
    state: restarted
    enabled: true
  become: true
- name: start promtail
  ansible.builtin.service:
    name: promtail
    state: restarted
    enabled: true
  become: true
