---
- name: Create kube group
  ansible.builtin.group:
    name: kube
    state: present
- name: Create config directory
  ansible.builtin.file:
    state: directory
    dest: "{{ item.dir }}/.kube"
    group: kube
    owner: "{{ item.name }}"
    mode: ug+rwx
  loop: "{{ users }}"
- name: Fetch kube config
  ansible.builtin.fetch:
    src: "/etc/kubernetes/admin.conf"
    dest: "roles/k8s/files/"
    flat: true
  delegate_to: kcp01.breeze-blocks.net
- name: Copy kube config
  ansible.builtin.copy:
    src: "admin.conf"
    dest: "{{ item.dir}}/.kube/config"
    group: kube
    owner: "{{ item.name }}"
    mode: u+rw
  loop: "{{ users }}"
- name: Create kube user
  ansible.builtin.user:
    name: kube
    group: kube
    state: present
- name: Create kubeadm directory
  ansible.builtin.file:
    state: directory
    recurse: true
    dest: /etc/kubeadm
    owner: kube
    group: kube
    mode: ug+rwx,o+rx
- name: Copy reset config
  ansible.builtin.copy:
    src: reset.yaml
    dest: /etc/kubeadm/reset.yaml
    owner: kube
    group: kube
    mode: ugo+rw,ugo-x
- name: Create bootstrap token
  ansible.builtin.command:
    chdir: /etc/kubeadm
    cmd: kubeadm token create --description "{{ inventory_hostname }}"
  register: token
- name: Template token join config
  ansible.builtin.template:
    src: join.yaml
    dest: /etc/kubeadm/join.yaml
    owner: kube
    group: kube
    mode: ugo+rw,ugo-x
- name: Copy hosts info
  ansible.builtin.copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: ug+rw,o+r
- name: Reset node status
  ansible.builtin.command:
    chdir: /etc/kubeadm
    cmd: kubeadm reset --config reset.yaml
- name: Join existing cluster
  ansible.builtin.command:
    chdir: /etc/kubeadm
    cmd: kubeadm join --config join.yaml
    creates: /etc/kubernetes/admin.conf
  register: init_result
- name: Debug
  ansible.builtin.debug:
    var: init_result
- name: Create CNI dir
  ansible.builtin.file:
    state: directory
