---
- name: Install and configure Primary AD DC
  hosts: dc
  remote_user: duchess
  tasks:
    - name: Install samba packages
      community.general.pacman:
        name: "{{ item }}"
        state: present
      become: true
      loop:
        - krb5
        - ntp
        - python-dnspython
        - python-markdown
        - openresolv
        - samba
    - name: Copy the ntp.conf file
      ansible.builtin.copy:
        src: samba/ntp.conf
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: 'u+rw,g+r,o+r'
      become: true
    - name: Start the ntpd service
      ansible.builtin.service:
        enabled: true
        name: ntpd
        state: restarted
      become: true
    - name: Copy the smb.conf file
      ansible.builtin.copy:
        src: samba/smb.conf
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: 'u+rw,g+r,o+r'
      become: true
    - name: Copy the krb5.conf file
      ansible.builtin.copy:
        src: samba/krb5.conf
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: 'u+rw,g+r,o+r'
      become: true
    - name: Start the samba service
      ansible.builtin.service:
        enabled: true
        name: samba
        state: restarted
      become: true
    - name: Create the sambashare group
      ansible.builtin.group:
        name: sambashare
        state: present
      become: true
    - name: Update user group
      ansible.builtin.user:
        name: duchess
        append: true
        groups: sambashare
      become: true
