---
- name: Create required group
  ansible.builtin.group:
    name: kube
    state: present
- name: Create required user
  ansible.builtin.user:
    name: kube
    state: present
    system: true
- name: Add local provisioner directory
  ansible.builtin.file:
    dest: /mnt/disks
    state: directory
    owner: kube
    group: kube
    mode: ug+rwx
- name: Upgrade packages
  community.general.pacman:
    state: present
    update_cache: true
    upgrade: true
- name: Install LVM package
  community.general.pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - lvm2
    - parted
    - nfs-utils
- name: Start NFS services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - nfs-idmapd
    - nfs-mountd
    - nfs-server
    - nfsdcld
    - lvm2-monitor
- name: Create a new primary partition for LVM
  community.general.parted:
    device: "{{ volumes_devices[inventory_hostname].usb.device }}"
    flags:
      - lvm
    label: gpt
    name: usb
    number: 1
    part_end: 100%
    state: present
- name: Create a LVM group
  community.general.lvg:
    vg: vg.usb
    pvs: "{{ volumes_devices[inventory_hostname].usb.device }}1"
    state: present
- name: Create LV
  community.general.lvol:
    vg: vg.usb
    lv: nfs
    size: 16G
- name: Format nfs volume
  community.general.filesystem:
    fstype: btrfs
    state: present
    dev: /dev/vg.usb/nfs
- name: Mount NFS for export from LV
  ansible.posix.mount:
    boot: true
    fstype: btrfs
    src: /dev/vg.usb/nfs
    path: /mnt/disks/nfs
    state: mounted
- name: Copy exports
  ansible.builtin.copy:
    src: exports
    dest: /etc/exports
    owner: root
    group: root
    mode: ug+rw
- name: Restart NFS
  ansible.builtin.service:
    name: nfs-server
    state: restarted
